=== 0003088/gt-gui-test/xmlschema/elektra.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- By RÃ©mi <remipouak@yahoo.fr> -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.libelektra.org"
	targetNamespace="http://www.libelektra.org"
	attributeFormDefault="unqualified"
	elementFormDefault="qualified">
	
	<xsd:element name="keyset"         type="KeySet_type"/>

	<xsd:complexType name="KeySet_type">
		<xsd:sequence>
			<xsd:element name="key"        minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="keyset"     minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	
		<xsd:attribute name="parent"   type="xsd:string"   use="optional">
			<xsd:annotation>
				<xsd:documentation>A parent indicates a directory key name that contains the keys under this KeySet. But, if some key happens to have an absolute name and is inside a keyset element, its absolute name wins.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:element name="key"            type="Key_type"/>
	
	<xsd:complexType name="Key_type">
		<xsd:sequence>
			<xsd:element name="value"      minOccurs="0"/>
			<xsd:element name="comment"    minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>This is CDATA, but I think it could be a xsd:string</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="key"        minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>

		<xsd:attribute name="id"       type="xsd:ID"       use="optional"/>
		<xsd:attribute name="name"     type="xsd:string"   use="optional">
			<xsd:annotation>
				<xsd:documentation>A key must have a name (absolute) or a basename (relative). If both appear, the absolute name wins.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="parent"   type="xsd:string"   use="optional">
			<xsd:annotation>
				<xsd:documentation>A parent can't appear in the same entry that has an absolute name. If parent appears together, name wins.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="basename" type="xsd:string"   use="optional">
			<xsd:annotation>
				<xsd:documentation>A basename can't appear in the same entry that has an absolute name. If basename appears together, name wins. Absolute name = parent + basename.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="value" type="xsd:string"   use="optional">
			<xsd:annotation>
				<xsd:documentation>Short values can be put as an attribute in the key element, to improve readability. But, if a value element appears latter, it wins over the attribute.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		
		<xsd:attribute name="type"     type="value_type"   use="optional" default="string"/>
		<xsd:attribute name="uid"      type="xsd:string"   use="optional"/>
		<xsd:attribute name="gid"      type="xsd:string"   use="optional"/>
		<xsd:attribute name="mode"     type="mode_type"    use="optional"/>
		<xsd:attribute name="atime"    type="xsd:dateTime" use="optional"/>
		<xsd:attribute name="ctime"    type="xsd:dateTime" use="optional"/>
		<xsd:attribute name="mtime"    type="xsd:dateTime" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="value_type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]*|undefined|string|binary|directory|link"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="mode_type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-7]{4}"/>
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== 0003088/gt-gui-test/doc/specs/network.xml
<?xml version="1.0" encoding="UTF-8"?>


<!-- Generated by Elektra API. Total of 20 keys. -->



<keyset parent="system/network"
        xmlns="http://elektra.sourceforge.net"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://elektra.sourceforge.net elektra.xsd">


<key basename="hostname"
     type="string" mode="0664">

     <value><![CDATA[example.domain.com]]></value>
     <comment><![CDATA[The fully qualified host name]]></comment>
</key>





<key basename="interfaces"
     type="directory" mode="0775">
</key>





<key basename="interfaces/LoopBack"
     type="directory" mode="0775">
</key>





<key basename="interfaces/LoopBack/broadcast"
     type="string" mode="0664">

     <value><![CDATA[127.255.255.255]]></value>
     <comment><![CDATA[If you're having problems with gated making 127.0.0.0/8 a martian, you can change this to something else (255.255.255.255, for example).
]]></comment>
</key>





<key basename="interfaces/LoopBack/device"
     type="string" mode="0664">

     <value><![CDATA[lo]]></value>
</key>





<key basename="interfaces/LoopBack/ip"
     type="string" mode="0664">

     <value><![CDATA[127.0.0.1]]></value>
     <comment><![CDATA[The fixed IP address of this interface.]]></comment>
</key>





<key basename="interfaces/LoopBack/netmask"
     type="string" mode="0664">

     <value><![CDATA[255.0.0.0]]></value>
</key>





<key basename="interfaces/LoopBack/onboot"
     type="string" mode="0664">

     <value><![CDATA[1]]></value>
     <comment><![CDATA[1 for automatic activation on boot
0 for only manual]]></comment>
</key>





<key basename="interfaces/SymbolicName1"
     type="directory" mode="0775">
</key>





<key basename="interfaces/SymbolicName1/HWaddress"
     type="string" mode="0664">

     <value><![CDATA[00:0D:60:12:A8:C6]]></value>
     <comment><![CDATA[The MAC address of this network interface]]></comment>
</key>





<key basename="interfaces/SymbolicName1/bootproto"
     type="string" mode="0664">

     <value><![CDATA[dhcp]]></value>
     <comment><![CDATA[The protocol type to be used to configure this interface. DHCP, BOOTP or static.]]></comment>
</key>





<key basename="interfaces/SymbolicName1/device"
     type="string" mode="0664">

     <value><![CDATA[eth0]]></value>
     <comment><![CDATA[The UNIX device name.]]></comment>
</key>





<key basename="interfaces/SymbolicName1/dhcphostname"
     type="string" mode="0664">

     <value><![CDATA[something.domain.com]]></value>
     <comment><![CDATA[The hostname we'll tell to the DHCP server, for dynDNS purposes.]]></comment>
</key>





<key basename="interfaces/SymbolicName1/ipv6init"
     type="string" mode="0664">

     <value><![CDATA[0]]></value>
     <comment><![CDATA[Weather this interface should be initialized with IPv6 too.]]></comment>
</key>





<key basename="interfaces/SymbolicName1/onboot"
     type="string" mode="0664">

     <value><![CDATA[1]]></value>
     <comment><![CDATA[1 for automatic activation on boot
0 for only manual]]></comment>
</key>





<key basename="interfaces/SymbolicName1/type"
     type="string" mode="0664">

     <value><![CDATA[ethernet]]></value>
     <comment><![CDATA[The phisical type of this network interface. Ethernet, Wireless, TokenRing, etc]]></comment>
</key>





<key basename="interfaces/SymbolicName1/usercontrol"
     type="string" mode="0664">

     <value><![CDATA[1]]></value>
     <comment><![CDATA[1 to let regular users control this interface
0 to be controled only by root]]></comment>
</key>





<key basename="interfaces/SymbolicName2"
     type="directory" mode="0775">
</key>





<key basename="nameserver"
     type="string" mode="0664">

     <value><![CDATA[ns1.domain.com, ns2.domain.com, ns1.organization.org]]></value>
     <comment><![CDATA[Comma separated list of name servers.]]></comment>
</key>





<key basename="search"
     type="string" mode="0664">

     <value><![CDATA[domain.com, sub1.domain.com, sub2.domain.com, domain2.com]]></value>
     <comment><![CDATA[Comma separated search domains.
Domains that will be tested together with a non FQDN host.]]></comment>
</key>





</keyset>

=== 0003088/gt-gui-test/doc/specs/env.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Subversion stuff

$Id$

-->

<!--

This specification-by-example defines an easier, more direct and more precise
way for applications to set aliases and env vars for a user session.

It will, in some ways, substitute the functionality of the files

	/etc/profile
	~/.profile
	~/.bashrc
	~/.bash_profile

Although on those files some can add code and some logic to define env vars,
this key schema is usefull when you just want to set environments in an
atomic way.

The /etc/profile.d/elektraenv.sh script loads the environments declared by
the keys in this schema.

The key hierarchy proposed (as examples) is:

Systemwide environments, as in /etc/profile:
	system/
	  env/
	    env1/
	      JAVA_HOME              = /opt/IBMJava2
	    env2/
	      PATH                   = $PATH:$JAVA_HOME/bin
	      LIBPATH                = $LIBPATH:$JAVA_HOME/lib
	    env3/
	      EDITOR                 = vi
	    alias/
	      ll                     = ls -l

User specific environment (loaded after system's), as in ~/.profile
	user/
	  env/
	    env1/
	    env2/
	      PATH                   = $PATH:~/bin
	      LIBPATH                = $LIBPATH:~/lib
	    env3/
	      PS1                    = \h:\w\$ 
	      EDITOR                 = kate
	    alias/
	      ls                     = ls -Fh -color=auto
	      ll                     = ls -l -Fh -color=auto
	      vi                     = gvim -x

Note that we have env1, env2 and env3 levels.
Thats because a script has a natural order for the things to happen, so we
can easily define $PATH using $JAVA_HOME, but after defining $JAVA_HOME.
Since there is no such natural order when accessing keys and values, the
elektraenv script will fetch env1, env2, env3 in this order, then envvars
can be defined dependent on previously defined other envvars, as
with $PATH depending on $JAVA_HOME.

In addition, the elektraenv script will fetch system/env keys before it
fetches user/env keys.

Avi Alkalay <avi@unix.sh>
Nov 2005

-->

<keyset xmlns="http://elektra.sourceforge.net"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://elektra.sourceforge.net elektra.xsd">

<!-- The systemwide environment and aliases -->
	<keyset parent="system/env/env1">
		<key basename="JAVA_HOME" value="/opt/IBMJava2"/>
	</keyset>


	<keyset parent="system/env/env2">
		<key basename="PATH">
			<value>$PATH:$JAVA_HOME/bin</value>
			<comment>Since we are under env2, and $JAVA_HOME was defined in env1, at this point, $JAVA_HOME is already set.</comment>
		</key>
		
		<key basename="LIBPATH" value="$LIBPATH:$JAVA_HOME/lib"/>
	</keyset>


	<keyset parent="system/env/env3">
		<key basename="EDITOR" value="vi"/>
	</keyset>


	<keyset parent="system/env/alias">
		<key basename="ll" value="ls -l"/>
	</keyset>




<!-- The user specific environment and aliases -->
	<keyset parent="user/env/env2">
		<key basename="PATH"    value="$PATH:~/bin"/>
		<key basename="LIBPATH" value="$LIBPATH:~/lib"/>
	</keyset>
	
	
	<keyset parent="user/env/env3">
		<key basename="PS1"    value="\h:\w\$ "/>
		<key basename="EDITOR" value="kate"/>
	</keyset>
		
		
	<keyset parent="user/env/alias">
		<key basename="ls" value="ls -Fh --color=tty"/>
		<key basename="ll" value="ls -l -Fh --color=tty"/>
		<key basename="vi" value="gvim -x"/>
	</keyset>

</keyset>

=== 0003088/gt-gui-test/example/hierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>



<!--
	Subversion stuff.
	
	$Id: keyset.xml 175 2005-01-27 08:28:07Z aviram $
	$LastChangedBy: aviram $
	
 -->


<keyset xmlns="http://elektra.sourceforge.net"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://elektra.sourceforge.net elektra.xsd"

		parent="user/tmp">

	<!-- The wrapping keyset is not really necessary. The key element
		 can be a root key -->
	
	<key basename="dir1">
		<key basename="xyz">
			<value>abc</value>
			<comment>comment1</comment>
		</key>
		<key basename="abc">
			<value>xyz</value>
			<comment>comment1</comment>
		</key>
		<key basename="dir2">
			<key basename="def">
				<value>cecece</value>
			</key>
			<key basename="uvw">
				<value>tatata</value>
			</key>
		</key>
	</key>
</keyset>

=== 0003088/gt-gui-test/doc/specs/signature.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Subversion stuff

$Id$

-->

<!--

The purpose of this specification-by-example is to define a standard way for systems to provide their own signature.
It is important because today there is no safe way for somebody (a program) to know exactly on which
OS (platform, version, update level, edition) it is running.

This is particulary useful for installation programs, when they must take decision about where to put files they'll
install, since each OS have slight differences about their filesystem organization, etc.

Its purpose is similar to the files installed by redhat-release or SuSE-release packages, but better:

/etc/issue
/etc/issue.net
/etc/redhat-release

This is a very simple structure, and here follows the signature for a Red Hat Enterprise Linux 4 update 2 (Nanant):

system/signature
  provider     = Red Hat
  os           = Linux
  type         = redhat
  edition      = AS
  version      = 4
  update       = 2
  architecture = ia32
  readable     = Red Hat Enterprise Linux 4 AS update 2 (Nanant)
  releasename  = Nanant
  url          = http://www.redhat.com/




A Novell Linux Desktop would have this signature:

system/signature
  provider     = Novell
  os           = Linux
  type         = suse
  edition      = NLD
  version      = 10
  update       = 0
  architecture = ia32
  readable     = Novell Linux Desktop
  url          = http://www.novell.com/



A Fedora 4 system for Opteron processos would be:

system/signature
  provider     = Fedora
  os           = Linux
  type         = redhat
  version      = 4
  architecture = x86_64
  readable     = Fedora Core 4
  url          = http://fedora.redhat.com/



Avi Alkalay
<avi at unix.sh>
Nov 2005

-->

<keyset xmlns="http://www.libelektra.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.libelektra.org elektra.xsd"

        parent="system/signature">


	<key basename="provider">
		<value>Red Hat</value>
		<comment>The company or organization that provides this operating system.</comment>
		<comment>Common values would be SuSE, Debian, CetnOS, Microsoft, etc.</comment>
	</key>






	<key basename="os">
		<value>Linux</value>
		<comment>The simple name of this OS. Could be "OpenBSD", "Windows", etc</comment>
	</key>






	<key basename="type">
		<value>redhat</value>
		<comment>A name for whom the system looks like.</comment>
		<comment>This is the most important key since it provides the hint about the filesystem layout, packaging naming conventions, etc</comment>
		<comment>Could be "redhat" for RHEL, CentOS, Fedora, Mandriva, Whitebox, Scientific Linux, etc.</comment>
		<comment>"debian" for Debian, Ubuntu, KUbuntu and all Debian-derived distro's</comment>
		<comment>"BSD" for all *BSD systems</comment>
		<comment>"suse" for SLES, OpenSuSE and Novell Linux Desktop</comment>
		<comment>Or "slackware", "aix", "solaris" etc for other systems</comment>
	</key>






	<key basename="readable">
		<value>Red Hat Enterprise Linux 4 AS</value>
		<comment>A nice human readable system name.</comment>
	</key>






	<key basename="releasename">
		<value>Nanant</value>
		<comment>An internal name that providers use to give to their products.</comment>
		<comment>Could be "Potato" for Debian, "Vista" for Windows, etc.</comment>
	</key>






	<key basename="edition">
		<value>AS</value>
		<comment>The edition of this OS. Common values are "Home Edition", "ES", "WS", Professional, etc</comment>
	</key>








	<key basename="version">
		<value>4</value>
		<comment>The version of this OS.</comment>
		<comment>Could be "95" or "2000" for popular Windows versions, "7.3" for old Red Hat versions, etc.</comment>
	</key>









	<key basename="update">
		<value>2</value>
		<comment>The update or patch level of a system. Could be "SP3" for Windows systems, etc.</comment>
	</key>









	<key basename="architecture">
		<value>ia32</value>
		<comment>The platform this OS is installed on. Popular names are "x86_64", "ppc", "s390", "s390x", "sparc", "ia64".</comment>
	</key>




	<key basename="url">
		<value>http://www.redhat.com</value>
		<comment>Some URL the provider wants to be published.</comment>
	</key>

</keyset>
